name: wallspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_downloader: ^0.31.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/Animals.jpg
    - images/Art.jpg
    - images/Astro.jpg
    - images/Cars.jpg
    - images/Games.jpg
    - images/Nature.jpg
